- name: 卸载apt/yum安装的ntp/chrony
  package: name={{ item }} state=absent
  with_items:
  - ntp
  - chrony
  ignore_errors: true

- name: 停止systemd-timesyncd.service
  service: name=systemd-timesyncd state=stopped enabled=no
  when: ansible_distribution == "Ubuntu"
  ignore_errors: true

- name: 配置 chrony server
  template: src=chrony-server.conf.j2 dest=/etc/chrony.conf
  when: 'inventory_hostname == groups.chrony[0]'

- name: 配置 chrony client
  template: src=chrony-client.conf.j2 dest=/etc/chrony.conf
  when: 'inventory_hostname != groups.chrony[0]'

- name: 生成 chrony service 文件
  template: src=chrony.service.j2 dest=/etc/systemd/system/chrony.service

- name: daemon-reload
  shell: systemctl daemon-reload

- name: 开机启用chrony服务
  shell: systemctl enable chrony
  ignore_errors: true

- name: 开启chrony服务
  shell: systemctl restart chrony
